---
# tasks file for remmina

  - name: Install apt packages
    apt:
      name: "{{ item }}"
    when:
      - ansible_distribution == "Debian"
    with_items:
      - remmina
      - remmina-plugin-rdp
      - remmina-plugin-vnc
