---
# tasks file for remmina

  - name: Install apt packages
    apt:
      name:
        - remmina
        - remmina-plugin-rdp
        - remmina-plugin-vnc
    when:
      - ansible_distribution == "Debian"
