---
# tasks file for aws-cli

  - name: Install pip packages
    pip:
      name:
        - awscli
        - docutils
      state: present
      extra_args: --upgrade --user
    become_user: "{{ user }}"
