---
# tasks file for nvm

  - name: Check NVM is installed
    shell: '[ -d /home/{{ user }}/.nvm ] && bash -lc nvm'
    become_user: "{{ user }}"
    register: nvm_installed
    ignore_errors: yes
  - name: Install NVM
    git:
      repo: https://github.com/creationix/nvm.git
      dest: /home/{{ user }}/.nvm
      version: v0.33.2
    become_user: "{{ user }}"
    when:
      - nvm_installed|failed
  - name: Setup NVM
    lineinfile:
      dest: /home/{{ user }}/.bashrc
      line: |
              export NVM_DIR="${HOME}/.nvm"
              [ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"
              [ -s "${NVM_DIR}/bash_completion" ] && \. "${NVM_DIR}/bash_completion"
      state: present
    become_user: "{{ user }}"
    when:
      - nvm_installed|failed
