- hosts: all
  become: yes
  vars:
    thinkpad: no
    mba11: no
  roles:
    - bash-it
    - docker
    - keybase
    - nvm
    - packer
    - powerline-font
    - remmina
    - spacemacs
    - vagrant
  tasks:
  - name: Install requirements for APT (Debian)
    apt: name={{ item }} state=present
    when: ansible_distribution == 'Debian'
    with_items:
     - apt-transport-https
     - software-properties-common

  - name: Add apt repositories keys (Common)
    apt_key: keyserver={{ item.server }} id={{ item.id }}
    with_items:
      - { server: 'keyserver.ubuntu.com', id: 'D2C19886' }
      - { server: 'keys.gnupg.net', id: '6BF18B15' }
      - { server: 'keyserver.ubuntu.com', id: '8231B6DD' }
      - { server: 'pgp.mit.edu', id: '5044912E' }
      - { server: 'ha.pool.sks-keyservers.net', id: 'F4E3FBBE' }

  - name: Add VirtualBox apt repository keys
    apt_key: url="https://www.virtualbox.org/download/oracle_vbox_2016.asc"

  - name: Add apt repositories (Debian)
    apt_repository: repo='{{ item }}'
    when: ansible_distribution == 'Debian'
    register: new_apt_repos_added
    with_items:
      - 'deb http://http.debian.net/debian stretch main contrib non-free'
      - 'deb http://repository.spotify.com stable non-free'
      - 'deb http://download.virtualbox.org/virtualbox/debian stretch contrib'
      - 'deb http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu xenial main'

  - name: Add apt repositories (non-Debian)
    apt_repository: repo='{{ item }}'
    when: ansible_distribution != 'Debian'
    register: new_non_deb_apt_repos_added
    with_items:
      - 'deb http://repository.spotify.com stable non-free'
      - 'ppa:nilarimogard/webupd8'
      - 'ppa:remmina-ppa-team/remmina-next'
      - 'ppa:zeal-developers/ppa'
      - 'ppa:rael-gc/scudcloud'

  - name: Update apt caches
    apt: update_cache=yes cache_valid_time=86400
    register: apt_cache_updated

  - name: Update apt caches (Forced)
    apt: update_cache=yes
    when:
      - new_apt_repos_added|changed or new_non_deb_apt_repos_added|changed
      - not apt_cache_updated|changed

  - name: Detect PCI devices
    shell: lspci
    register: lspci

  - name: Set as MacBook Air 11
    set_fact: mba11=yes
    when: lspci.stdout.find('BCM43224') > 0

  - name: Detect USB devices
    shell: lsusb
    register: lsusb
    ignore_errors: True

  - name: Set as Lenovo Thinkpad T430s
    set_fact: thinkpad=yes
    when: lsusb.stdout.find('thinkpad') > 0

  - name: Install BCM43224 firmware (Debian and BCM43224)
    apt: name=firmware-brcm80211
    when: ansible_distribution == 'Debian' and mba11

  - name: Install iwlwifi firmware (Debian and Lenovo)
    apt: name=firmware-iwlwifi
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Install tpb (Lenovo Thinkpad)
    apt: name=tpb state=present
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Enable Screen brightness control (Lenovo Thinkpad)
    lineinfile: dest=/etc/default/grub line='GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} acpi_osi=Linux acpi_backlight=vendor"'
    register: grub_update
    when: ansible_distribution == 'Debian' and thinkpad
  - name: Update GRUB for Screen brightness control (Lenovo Thinkpad)
    shell: update-grub
    become: True
    when: ansible_distribution == 'Debian' and thinkpad and not grub_update|failed
  - name: Setup X11 Screen brightness controls (Lenovo Thinkpad)
    template: src=templates/20-intel.conf.j2 dest=/usr/share/X11/xorg.conf.d/20-intel.conf
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Check Telegram is installed
    shell: which telegram
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Download Telegram package
    get_url: url=https://tdesktop.com/linux dest=/tmp/telegram.tar.xz
    when: result|failed
  - name: Unpack Telegram
    shell: tar -xJf /tmp/telegram.tar.xz chdir=/opt creates=/opt/Telegram
    when: result|failed
  - name: Install Telegram
    shell: ln -s /opt/Telegram/Telegram /usr/bin/telegram creates=/usr/bin/telegram
    when: result|failed
  - name: Setup Telegram Desktop icon
    copy: src=files/telegram.png dest=/usr/share/icons/hicolor/128x128/apps/telegram.png
    when: result|failed
  - name: Setup Telegram Desktop info
    template: src=templates/telegram.desktop.j2 dest=/usr/share/applications/telegram.desktop
    when: result|failed
  - name: Remove Telegram package
    file: path=/tmp/telegram.tar.xz state=absent

  - name: Check Chrome is installed
    shell: which google-chrome
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Download Chrome package
    get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb dest=/tmp/chrome.deb
    when: result|failed
  - name: Install Chrome
    apt: deb=/tmp/chrome.deb
    when: result|failed
  - name: Setup Chrome alias
    lineinfile: dest=/home/{{ user }}/.bashrc line='alias chrome=google-chrome'
  - name: Remove Chrome package
    file: path=/tmp/chrome.deb state=absent

  - name: Check Go is installed
    shell: ls /usr/local/go/bin/go
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Download Go package
    get_url: url=https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz dest=/tmp/go.tgz
    when: result|failed
  - name: Unpack Go
    shell: tar -xzf /tmp/go.tgz chdir=/usr/local creates=/usr/local/go
  - name: Install Go
    lineinfile: dest=/home/{{ user }}/.bashrc line='export PATH=$PATH:/usr/local/go/bin'
  - name: Setup Go
    lineinfile: dest=/home/{{ user }}/.bashrc line='export GOPATH=$HOME'
  - name: Remove Go package
    file: path=/tmp/go.tgz state=absent

  - name: Check Hub is installed
    shell: ls /home/{{ user }}/bin/hub
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Install Hub
    shell: GOPATH=/home/{{ user }} /usr/local/go/bin/go get github.com/github/hub creates=/home/{{ user }}/bin/hub
    become_user: '{{ user }}'
    when: result|failed
  - name: Setup Hub
    lineinfile: dest=/home/{{ user }}/.bashrc line='export PATH=$PATH:/home/{{ user }}/bin'
  - name: Replace Git with Hub
    lineinfile: dest=/home/{{ user }}/.bashrc line='alias git=hub'

  - name: Check Heroku Toolbelt is installed
    shell:  which heroku && heroku
    become_user: '{{ user }}'
    register: heroku_installed
    ignore_errors: True
  - name: Download Heroku Toolbelt installer
    get_url: url=https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz dest=/tmp/heroku.tar.gz
    register: heroku_download
    ignore_errors: True
    when: heroku_installed|failed
  - name: Get Heroku Installer
    shell: curl https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz > /tmp/heroku.tar.gz
    when: heroku_download|failed
  - name: Unarchive Heroku Installer
    unarchive: src=/tmp/heroku.tar.gz dest=/usr/local/lib
    when: heroku_installed|failed
  - name: Install Heroku
    shell: /usr/local/lib/heroku/install
    when: heroku_installed|failed

  - name: Check Dropbox is installed
    shell: ls /home/{{ user }}/Dropbox
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Install Dropbox (Ubuntu)
    apt: name=nautilus-dropbox
    when: result|failed and ansible_distribution == 'Ubuntu'
  - name: Setup Dropbox (Ubuntu)
    shell: dropbox stop && XDG_CURRENT_DESKTOP=Unity dropbox start -i
    become_user: '{{ user }}'
    when: result|failed and ansible_distribution == 'Ubuntu'
  - name: Rename Dropbox client (Ubuntu)
    shell: mv /usr/bin/dropbox /usr/bin/dropbox.py
    when: result|failed and ansible_distribution == 'Ubuntu'
  - name: Put Dropbox client wrapper (Ubuntu)
    template: src=templates/dropbox.j2 dest=/usr/bin/dropbox mode=0755
    when: result|failed and ansible_distribution == 'Ubuntu'
  - name: Download Dropbox (Debian)
    get_url: url=https://www.dropbox.com/download?plat=lnx.x86_64 dest=/tmp/dropbox.tar.gz
    when: result|failed and ansible_distribution == 'Debian'
  - name: Unarchive Dropbox (Debian)
    unarchive: src=/tmp/dropbox.tar.gz dest=/home/{{ user }}
    become_user: '{{ user }}'
    when: result|failed and ansible_distribution == 'Debian'
  - name: Setup Dropbox (Debian)
    shell: nohup /home/{{ user }}/.dropbox-dist/dropboxd &
    become_user: '{{ user }}'
    when: result|failed and ansible_distribution == 'Debian'

  - name: Check Miniconda is installed
    shell: ls /home/{{ user }}/.miniconda
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Download Miniconda installer
    get_url: url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh dest=/tmp/Miniconda.sh
    when: result|failed
  - name: Install Miniconda
    shell: bash -lc "bash /tmp/Miniconda.sh -b -p /home/{{ user }}/.miniconda"
    become_user: '{{ user }}'
    when: result|failed
  - name: Setup Conda
    lineinfile: dest=/home/{{ user }}/.bashrc line='export PATH=$PATH:/home/{{ user }}/.miniconda/bin'
    when: result|failed
  - name: Remove Miniconda installer
    file: path=/tmp/Miniconda.sh state=absent

  - name: Check RVM is installed
    shell: bash -lc "rvm"
    become_user: '{{ user }}'
    register: result
    ignore_errors: True
  - name: Setup RVM keyserver
    shell: gpg --keyserver hkp://pgp.mit.edu --recv-keys D39DC0E3
    when: result|failed
  - name: Download RVM installer
    get_url: url=https://get.rvm.io dest=/tmp/rvm.sh
    when: result|failed
  - name: Install cURL
    apt: name=curl
    when: ansible_distribution == 'Debian'
  - name: Install RVM
    shell: bash /tmp/rvm.sh master --ruby=1.9.3 --ruby=2.2.1 --ruby=2.1.5
    when: result|failed
  - name: Setup RVM in session
    lineinfile: dest=/home/{{ user }}/.bashrc line='. /etc/profile.d/rvm.sh'
  - name: Setup PATH for RVM
    lineinfile: dest=/home/{{ user }}/.bashrc line='export PATH=/usr/local/rvm/gems/ruby-1.9.3-p551/bin:$PATH'

  - name: Install thefuck requirements
    apt: name=python-dev

  - name: Install LibreOffice
    apt: name={{ item }}
    with_items:
      - fonts-opensymbol
      - hyphen-ca
      - hyphen-en-us
      - libreoffice
      - myspell-ca
      - myspell-es
      - mythes-ca
      - mythes-en-us

  - name: Install Caffeine Plus
    apt: name=caffeine-plus state=present
    when: ansible_distribution != 'Debian'
  - name: Install Caffeine
    apt: name=caffeine state=present
    when: ansible_distribution == 'Debian'

  - name: Install pip packages
    pip: name={{ item }}
    with_items:
      - psutil
      - thefuck

  - name: Install apt packages
    apt: name={{ item }}
    when: ansible_distribution != 'Debian'
    with_items:
      - firefox
      - unetbootin

  - name: Check LibSSL install
    shell: dpkg -l | grep libssl1.0.0
    register: libssl_installed
    ignore_errors: True
  - name: Install LibSSL1.0 from Jessie
    apt: deb="http://ftp.es.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb"
    when: libssl_installed|failed

  - name: Install apt packages
    apt: name={{ item }}
    with_items:
      - awesome
      - awesome-extra
      - calibre
      - dhcpcd5
      - gimp
      - gimp-data-extras
      - gimp-dcraw
      - gimp-gap
      - gimp-gluas
      - gimp-gmic
      - gimp-gutenprint
      - gimp-lensfun
      - gimp-plugin-registry
      - gimp-texturize
      - gnome-disk-utility
      - htop
      - ipcalc
      - keepassx
      - pidgin
      - pidgin-guifications
      - pidgin-hotkeys
      - pidgin-themes
      - python-argcomplete
      - pwgen
      - scudcloud
      - spotify-client
      - terminator
      - virtualbox-5.1
      - vlc
      - wpasupplicant
      - xbacklight
      - zeal

  - name: Setup Awesome in XSession
    template: src=templates/Xsession.j2 dest=/home/{{ user }}/.Xsession
    become_user: '{{ user }}'
  - name: Create Awesome config dir
    file: path=/home/{{ user }}/.config/awesome state=directory mode=0755 owner={{ user }} group={{ user }}
  - name: Setup Awesome
    template: src=templates/awesome.lua.j2 dest=/home/{{ user }}/.config/awesome/rc.lua
    become_user: '{{ user }}'

  - name: Setup Util scripts
    template: src=templates/{{ item }}.j2 dest=/home/{{ user }}/bin/{{ item }} mode=0755
    become_user: '{{ user }}'
    with_items:
     - wifi
     - volume
