- hosts: all
  become: yes
  vars:
    thinkpad: no
    mba11: no
  roles:
    - bash-it
    - common
    - conda
    - docker
    - dropbox
    - go
    - google-chrome
    - heroku-cli
    - hub
    - keybase
    - nvm
    - packer
    - powerline-font
    - remmina
    - rvm
    - spacemacs
    - spotify
    - telegram
    - vagrant
    - virtualbox
  tasks:

  - name: Add apt repositories keys (Common)
    apt_key: keyserver={{ item.server }} id={{ item.id }}
    with_items:
      - { server: 'keys.gnupg.net', id: '6BF18B15' }
      - { server: 'keyserver.ubuntu.com', id: '8231B6DD' }
      - { server: 'pgp.mit.edu', id: '5044912E' }
      - { server: 'ha.pool.sks-keyservers.net', id: 'F4E3FBBE' }

  - name: Add apt repositories (Debian)
    apt_repository: repo='{{ item }}'
    when: ansible_distribution == 'Debian'
    register: new_apt_repos_added
    with_items:
      - 'deb http://http.debian.net/debian stretch main contrib non-free'
      - 'deb http://ppa.launchpad.net/rael-gc/scudcloud/ubuntu xenial main'

  - name: Add apt repositories (non-Debian)
    apt_repository: repo='{{ item }}'
    when: ansible_distribution != 'Debian'
    register: new_non_deb_apt_repos_added
    with_items:
      - 'ppa:nilarimogard/webupd8'
      - 'ppa:remmina-ppa-team/remmina-next'
      - 'ppa:zeal-developers/ppa'
      - 'ppa:rael-gc/scudcloud'

  - name: Update apt caches
    apt: update_cache=yes cache_valid_time=86400
    register: apt_cache_updated

  - name: Update apt caches (Forced)
    apt: update_cache=yes
    when:
      - new_apt_repos_added|changed or new_non_deb_apt_repos_added|changed
      - not apt_cache_updated|changed

  - name: Detect PCI devices
    shell: lspci
    register: lspci

  - name: Set as MacBook Air 11
    set_fact: mba11=yes
    when: lspci.stdout.find('BCM43224') > 0

  - name: Detect USB devices
    shell: lsusb
    register: lsusb
    ignore_errors: True

  - name: Set as Lenovo Thinkpad T430s
    set_fact: thinkpad=yes
    when: lsusb.stdout.find('thinkpad') > 0

  - name: Install BCM43224 firmware (Debian and BCM43224)
    apt: name=firmware-brcm80211
    when: ansible_distribution == 'Debian' and mba11

  - name: Install iwlwifi firmware (Debian and Lenovo)
    apt: name=firmware-iwlwifi
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Install tpb (Lenovo Thinkpad)
    apt: name=tpb state=present
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Enable Screen brightness control (Lenovo Thinkpad)
    lineinfile: dest=/etc/default/grub line='GRUB_CMDLINE_LINUX_DEFAULT="${GRUB_CMDLINE_LINUX_DEFAULT} acpi_osi=Linux acpi_backlight=vendor"'
    register: grub_update
    when: ansible_distribution == 'Debian' and thinkpad
  - name: Update GRUB for Screen brightness control (Lenovo Thinkpad)
    shell: update-grub
    become: True
    when: ansible_distribution == 'Debian' and thinkpad and not grub_update|failed
  - name: Setup X11 Screen brightness controls (Lenovo Thinkpad)
    template: src=templates/20-intel.conf.j2 dest=/usr/share/X11/xorg.conf.d/20-intel.conf
    when: ansible_distribution == 'Debian' and thinkpad

  - name: Install thefuck requirements
    apt: name=python-dev

  - name: Install LibreOffice
    apt: name={{ item }}
    with_items:
      - fonts-opensymbol
      - hyphen-ca
      - hyphen-en-us
      - libreoffice
      - myspell-ca
      - myspell-es
      - mythes-ca
      - mythes-en-us

  - name: Install Caffeine Plus
    apt: name=caffeine-plus state=present
    when: ansible_distribution != 'Debian'
  - name: Install Caffeine
    apt: name=caffeine state=present
    when: ansible_distribution == 'Debian'

  - name: Install pip packages
    pip: name={{ item }}
    with_items:
      - psutil
      - thefuck

  - name: Install apt packages
    apt: name={{ item }}
    when: ansible_distribution != 'Debian'
    with_items:
      - firefox
      - unetbootin

  - name: Install apt packages
    apt: name={{ item }}
    with_items:
      - awesome
      - awesome-extra
      - calibre
      - dhcpcd5
      - gimp
      - gimp-data-extras
      - gimp-dcraw
      - gimp-gap
      - gimp-gluas
      - gimp-gmic
      - gimp-gutenprint
      - gimp-lensfun
      - gimp-plugin-registry
      - gimp-texturize
      - gnome-disk-utility
      - htop
      - ipcalc
      - keepassx
      - pidgin
      - pidgin-guifications
      - pidgin-hotkeys
      - pidgin-themes
      - python-argcomplete
      - pwgen
      - scudcloud
      - terminator
      - vlc
      - wpasupplicant
      - xbacklight
      - zeal

  - name: Setup Awesome in XSession
    template: src=templates/Xsession.j2 dest=/home/{{ user }}/.Xsession
    become_user: '{{ user }}'
  - name: Create Awesome config dir
    file: path=/home/{{ user }}/.config/awesome state=directory mode=0755 owner={{ user }} group={{ user }}
  - name: Setup Awesome
    template: src=templates/awesome.lua.j2 dest=/home/{{ user }}/.config/awesome/rc.lua
    become_user: '{{ user }}'

  - name: Setup Util scripts
    template: src=templates/{{ item }}.j2 dest=/home/{{ user }}/bin/{{ item }} mode=0755
    become_user: '{{ user }}'
    with_items:
     - wifi
     - volume
