- hosts: all
  become: yes
  vars:
    thinkpad: no
    mba11: no
  roles:
    - common
    - base
    - awesome
    - aws-cli
    - bash-it
    - calibre
    - caffeine
    - conda
    - displaylink
    - dropbox
    - ffmpeg
    - firefox
    - gimp
    - go
    - awless
    - google-chrome
    - heroku-cli
    - hub
    - jq
    - keepass
    - keybase
    - libav-tools
    - libre-office
    - nvm
    - openvpn
    - packer
    - pidgin
    - powerline-font
    - postgresql-client
    - redis-cli
    - remmina
    - rvm
    - slack
    - spacemacs
    - spotify
    - telegram
    - thefuck
    - vagrant
    - vim
    - virtualbox
    - youtube-dl
    - zeal
