---
# tasks file for telegram

  - name: Check Telegram is installed
    shell: /bin/bash -lc "which telegram"
    register: telegram_installed
    ignore_errors: yes
    become_user: "{{ user }}"
  - name: Download Telegram package
    get_url:
      url: https://tdesktop.com/linux
      dest: /tmp/telegram.tar.xz
    when:
      - telegram_installed|failed
  - name: Ensure ~/.local/share exists
    file:
      path: /home/{{ user }}/.local/share
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
  - name: Unpack Telegram
    shell: tar -xJf /tmp/telegram.tar.xz
    args:
      chdir: /home/{{ user }}/.local/share
      creates: /home/{{ user }}/.local/share/Telegram
    when:
      - telegram_installed|failed
    become_user: "{{ user }}"
  - name: Install Telegram
    shell: ln -s /home/{{ user }}/.local/share/Telegram/Telegram /home/{{ user }}/bin/telegram
    args:
      creates: /home/{{ user }}/bin/telegram
    when:
      - telegram_installed|failed
    become_user: "{{ user }}"
  - name: Remove Telegram package
    file:
      path: /tmp/telegram.tar.xz
      state: absent
    when:
      - telegram_installed|failed
