---
# tasks file for vagrant

  - name: Check Vagrant is installed
    shell: which vagrant
    register: vagrant_installed
    ignore_errors: yes
  - name: Download Vagrant deb package
    get_url:
      url: https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb
      dest: /tmp/vagrant.deb
    register: vagrant_download
    ignore_errors: yes
    when:
      - vagrant_installed|failed
  - name: Get Vagrant deb package
    shell: curl https://releases.hashicorp.com/vagrant/1.9.8/vagrant_1.9.8_x86_64.deb > /tmp/vagrant.deb
    when:
      - vagrant_download|failed
  - name: Install Vagrant
    apt:
      deb: /tmp/vagrant.deb
      state: present
    when:
      - vagrant_installed|failed
  - name: Remove Vagrant deb package
    file:
      path: /tmp/vagrant.deb
      state: absent
    when:
      - vagrant_installed|failed
