---
# tasks file for pidgin

  - name: Install apt packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - pidgin
      - pidgin-guifications
      - pidgin-hotkeys
      - pidgin-themes
