---
# tasks file for packer

  - name: Check Packer is installed
    shell: bash -lc "which packer"
    register: packer_installed
    ignore_errors: yes
  - name: Download Packer ZIP
    get_url:
      url: https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip
      dest: /tmp/packer.zip
    register: packer_download
    ignore_errors: yes
    when:
      - packer_installed is failed
  - name: Get Packer ZIP
    shell: curl https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip > /tmp/packer.zip
    when:
      - packer_download is failed
  - name: Install Packer
    unarchive:
      src: /tmp/packer.zip
      dest: /usr/local/bin
      creates: /usr/local/bin/packer
      owner: root
      group: root
      mode: 0755
    when:
      - packer_installed is failed
  - name: Remove Packer ZIP
    file:
      path: /tmp/packer.zip
      state: absent
    when:
      - packer_installed is failed
