---
# tasks file for zeal

  - name: Add apt repositories (non-Debian)
    apt_repository:
      repo: "{{ item }}"
      state: present
    when:
      - ansible_distribution != "Debian"
    register: new_non_deb_apt_repos_added
    with_items:
      - ppa:zeal-developers/ppa

  - name: Update apt caches (Forced)
    apt:
      update_cache: yes
    when:
      - new_non_deb_apt_repos_added|changed

  - name: Install apt packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - zeal
