---
# tasks file for aws-eb-cli

  - name: Install pip packages
    pip:
      name: "{{ item }}"
      state: present
      extra_args: --upgrade --user
    become_user: "{{ user }}"
    with_items:
      - awsebcli
