---
# tasks file for rvm

  - name: Check RVM is installed
    shell: bash -lc "rvm"
    become_user: "{{ user }}"
    register: rvm_installed
    ignore_errors: yes
  - name: Setup RVM keyserver
    shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
    when:
      - rvm_installed|failed
  - name: Download RVM installer
    get_url:
      url: https://get.rvm.io
      dest: /tmp/rvm.sh
    when:
      - rvm_installed|failed
  - name: Install cURL
    apt:
      name: curl
      state: present
    when:
      - ansible_distribution == "Debian"
  - name: Install RVM
    include_tasks: "roles/rvm/tasks/{{ rvm_install_mode }}_install.yml"
    when:
      - rvm_installed|failed
