---
# tasks file for unetbootin

  - name: Install apt packages
    apt:
      name: "{{ item }}"
      state: present
    when:
      - ansible_distribution != "Debian"
    with_items:
      - unetbootin
