---
# tasks file for virtualbox

  - name: Add VirtualBox apt repository keys
    apt_key:
      url: https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
      state: present

  - name: Add apt repositories (Debian)
    apt_repository:
      repo: "{{ item }}"
      state: present
    when:
      - ansible_distribution == "Debian"
    register: new_apt_repos_added
    with_items:
      - deb http://download.virtualbox.org/virtualbox/debian buster contrib
