---
# tasks file for thefuck

  - name: Install thefuck requirements
    apt:
      name: python-dev
      state: present
  - name: Install pip packages
    pip:
      name:
        - thefuck
      state: present
