---
# tasks file for go

  - name: Check Go is installed
    shell: ls /usr/local/go/bin/go
    become_user: "{{ user }}"
    register: go_installed
    ignore_errors: yes
  - name: Download Go package
    get_url:
      url: https://storage.googleapis.com/golang/go1.9.3.linux-amd64.tar.gz
      dest: /tmp/go.tgz
    when:
      - go_installed|failed
  - name: Unpack Go
    shell: tar -xzf /tmp/go.tgz
    args:
      chdir: /usr/local
      creates: /usr/local/go
    when:
      - go_installed|failed
  - name: Install Go
    lineinfile:
      dest: /home/{{ user }}/.bashrc
      line: export PATH=$PATH:/usr/local/go/bin
      state: present
    when:
      - go_installed|failed
  - name: Setup Go
    lineinfile:
      dest: /home/{{ user }}/.bashrc
      line: export GOPATH=$HOME
      state: present
    when:
      - go_installed|failed
  - name: Remove Go package
    file:
      path: /tmp/go.tgz
      state: absent
    when:
      - go_installed|failed
