---
# tasks file for heroku-cli

  - name: Check Heroku Toolbelt is installed
    shell:  which heroku && heroku
    become_user: "{{ user }}"
    register: heroku_installed
    ignore_errors: yes
  - name: Download Heroku Toolbelt installer
    get_url:
      url: https://cli-assets.heroku.com/install-ubuntu.sh
      dest: /tmp/heroku-install.sh
      owner: root
      group: root
      mode: 0755
    register: heroku_download
    ignore_errors: yes
    when:
      - heroku_installed is failed
  - name: Install Heroku
    shell: /tmp/heroku-install.sh
    when:
      - heroku_installed is failed
