---
# tasks file for dropbox

  - name: Check Dropbox is installed
    shell: ls /home/{{ user }}/.dropbox
    become_user: "{{ user }}"
    register: dropbox_installed
    ignore_errors: yes

  - name: Download Dropbox (Debian)
    get_url:
      url: https://www.dropbox.com/download?plat=lnx.x86_64
      dest: /tmp/dropbox.tar.gz
    when:
      - dropbox_installed is failed
      - ansible_distribution == "Debian"
  - name: Unarchive Dropbox (Debian)
    unarchive:
      src: /tmp/dropbox.tar.gz
      dest: /home/{{ user }}
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    when:
      - dropbox_installed is failed
      - ansible_distribution == "Debian"
  - name: Setup Dropbox (Debian)
    shell: nohup /home/{{ user }}/.dropbox-dist/dropboxd &
    become_user: "{{ user }}"
    when:
      - dropbox_installed is failed
      - ansible_distribution == "Debian"
  - name: Remove Dropbox package
    file:
      path: /tmp/dropbox.tar.gz
      state: absent
    when:
      - dropbox_installed is failed
      - ansible_distribution == "Debian"
