---
# tasks file for displaylink

  - name: Check DLM service is installed
    shell: test -f /lib/systemd/system/dlm.service
    become_user: "{{ user }}"
    register: result
    ignore_errors: yes
  - name: Install requirements
    apt:
      name: linux-source
      state: present
    when: result is failed
  - name: Clone DisplayLink installer into tmp
    git:
      repo: http://github.com/AdnanHodzic/displaylink-debian.git
      dest: /tmp/displaylink-debian
    become_user: "{{ user }}"
    when: result is failed
  - name: Install DisplayLink
    expect:
      command: /tmp/displaylink-debian/displaylink-debian.sh --install
      responses:
        (?i)and accept here: "Yes"
    become: yes
    when: result is failed
  - name: Stop DLM service
    service: name=dlm state=stopped
    when: result is failed
  - name: remove EVDI module
    shell: /sbin/modprobe -r evdi
    become: yes
    when: result is failed
  - name: Start DLM service
    service: name=dlm state=started
    when: result is failed
