---
# tasks file for common

  - name: Install requirements for APT (Debian)
    apt: name={{ item }} state=present
    when: ansible_distribution == 'Debian'
    with_items:
     - apt-transport-https
     - software-properties-common
