---
# tasks file for common

  - name: Install requirements for APT (Debian)
    apt:
      name: "{{ item }}"
      state: present
    when:
      - ansible_distribution == "Debian"
    with_items:
      - apt-transport-https
      - software-properties-common

  - include_tasks: "roles/{{ role }}/tasks/prepare_repos.yml"
    with_items:
      - "{{ role_names }}"
    register: new_repos_added
    loop_control:
      loop_var: role

  - name: Update apt caches (Forced)
    apt:
      update_cache: yes
    when:
      - new_repos_added|changed
