---
# tasks file for powerline-font

  - name: Configure MS TTF Core Fonts EULA to accepted
    debconf:
     name: ttf-mscorefonts-installer
     question: msttcorefonts/accepted-mscorefonts-eula
     value: yes
     vtype: select

  - name: Check Powerline font is required
    shell: ls /home/{{ user }}/.fonts/PowerlineSymbols.otf
    register: font_installed
    ignore_errors: yes
  - name: Make font dir
    file:
      path: /home/{{ user }}/.fonts
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    become_user: "{{ user }}"
    when:
      - font_installed is failed
  - name: Download Powerline font
    get_url:
      url: https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
      dest: /home/{{ user }}/.fonts
    become_user: "{{ user }}"
    when:
      - font_installed is failed
  - name: Make fontconfig dir
    file:
      path: /home/{{ user }}/.config/fontconfig/conf.d
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    become_user: "{{ user }}"
    when:
      - font_installed is failed
  - name: Download Powerline fontconfig file
    get_url:
      url: https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
      dest: /home/{{ user }}/.config/fontconfig/conf.d
    become_user: "{{ user }}"
    when:
      - font_installed is failed
  - name: Update font cache
    shell: fc-cache -vf /home/{{ user }}/.fonts
    become_user: "{{ user }}"
    when:
      - font_installed is failed
