---
# tasks file for docker

  - name: Install pip packages
    pip:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-compose

  - name: Install apt packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - docker-ce
