---
# tasks file for docker

  - name: Install pip packages
    pip:
      name:
        - docker-compose
      state: present

  - name: Install apt packages
    apt:
      name:
        - docker-ce
      state: present
