---
# tasks file for base

  - name: Calculate hardware profile for computer model
    set_fact:
      hw_hook: "{{ computer_model|lower|regex_replace(' ', '_')|regex_replace(',','_') }}"

  - include_tasks: "roles/base/tasks/hw_{{ hw_hook }}.yml"

  - name: Install pip packages
    pip:
      name:
        - psutil
      state: present

  - name: Install apt packages
    apt:
      name:
        - bash-completion
        - dhcpcd5
        - dnsutils
        - gnome-disk-utility
        - htop
        - ipcalc
        - libsox-fmt-mp3
        - python-argcomplete
        - pwgen
        - sox
        - terminator
        - vlc
        - whois
        - wpasupplicant
        - xbacklight
      state: present
