---
# tasks file for libre-office

  - name: Install LibreOffice
    apt:
      name:
        - fonts-opensymbol
        - hyphen-ca
        - hyphen-en-us
        - libreoffice
        - myspell-ca
        - myspell-es
        - mythes-ca
        - mythes-en-us
      state: present
