---
# tasks file for awesome

  - name: Install apt packages
    apt: name={{ item }}
    with_items:
      - awesome
      - awesome-extra

  - name: Setup Awesome in XSession
    template: src=templates/Xsession.j2 dest=/home/{{ user }}/.Xsession
    become_user: '{{ user }}'
  - name: Create Awesome config dir
    file: path=/home/{{ user }}/.config/awesome state=directory mode=0755 owner={{ user }} group={{ user }}
  - name: Setup Awesome
    template: src=templates/awesome.lua.j2 dest=/home/{{ user }}/.config/awesome/rc.lua
    become_user: '{{ user }}'

  - name: Setup Util scripts
    template: src=templates/{{ item }}.j2 dest=/home/{{ user }}/bin/{{ item }} mode=0755
    become_user: '{{ user }}'
    with_items:
     - wifi
     - volume
