---
# tasks file for awesome

  - name: Install apt packages
    apt:
      name:
        - awesome
        - awesome-extra
      state: present
  - name: Setup Awesome in XSession
    file:
      path: /home/{{ user }}/bin
      state: directory
      mode: 0755
      owner: "{{ user }}"
      group: "{{ user }}"
  - name: Setup Awesome in Xsession
    template:
      src: templates/Xsession.j2
      dest: /home/{{ user }}/.Xsession
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
  - name: Create Awesome config dir
    file:
      path: /home/{{ user }}/.config/awesome
      state: directory
      mode: 0755
      owner: "{{ user }}"
      group: "{{ user }}"
  - name: Clone Battery widget
    git:
      repo: https://github.com/velovix/awesome.battery-widget
      dest: /home/{{ user }}/.config/awesome/awesome.battery-widget
    become_user: "{{ user }}"
  - name: Setup Battery widget
    file:
      src: /home/{{ user }}/.config/awesome/awesome.battery-widget/battery-widget.lua
      path: /home/{{ user }}/.config/awesome/battery-widget.lua
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
      state: link
  - name: Clone Revelation
    git:
      repo: https://github.com/guotsuan/awesome-revelation
      dest: /home/{{ user }}/.config/awesome/revelation
    become_user: "{{ user }}"
  - name: Setup Awesome
    template:
      src: templates/awesome.lua.j2
      dest: /home/{{ user }}/.config/awesome/rc.lua
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
  - name: Setup Util scripts
    template:
      src: templates/{{ item }}.j2
      dest: /home/{{ user }}/bin/{{ item }}
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0755
    with_items:
     - wifi
     - volume
     - brightness
