---
# tasks file for gimp

  - name: Install apt packages
    apt:
      name:
        - gimp
        - gimp-data-extras
        - gimp-dcraw
        - gimp-gap
        - gimp-gluas
        - gimp-gmic
        - gimp-gutenprint
        - gimp-lensfun
        - gimp-plugin-registry
        - gimp-texturize
      state: present
