---
# tasks file for openvpn

  - name: Install openvpn
    apt:
      name:
       - openvpn
       - network-manager-openvpn-gnome
      state: present
    when:
      - ansible_distribution == "Debian"
